### ISSUE TITLE
Chunk options

### ISSUE THREAD

**Issue by ratnanil** [carmenpfoster/project#3]
I just has a look at your preliminary report. As I mentioned [here](https://moodle.zhaw.ch/mod/forum/discuss.php?d=53346&parent=86502), you shouldn't show your R code within your report. Apparently, you've already adjusted this via the chunk options in 465d6f7c147c04010af3dfceb60f9eb33cdda4c9, where you added `echo = FALSE, warning = FALSE, message = FALSE}` to every chunk. Remeber to re-knit your file to html and commit your html to github to see these changes online (on https://carmenpfoster.github.io/project/Semesterproject)

Just as an info: You could also have just added the following lines to the top of your script:
````
```{r, echo = FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
```
````

**Comment by carmenpfoster** [comment]
oh thanks for the advise, in the end we implemented it with the code at the beginning of the script
